select * from fd where kbci_no = '1300270'


SELECT M.KBCI_NO
	,CASE WHEN M.MI IS NULL THEN 
	 M.LNAME + ', ' + M.FNAME 
	 ELSE
	 M.LNAME + ', ' + M.FNAME + ' ' + ISNULL(M.MI,'') + '.'
	 END NAME
	,FDR.BALANCE
FROM MEMBERS M
RIGHT JOIN (
	SELECT KBCI_NO
		,BALANCE
	FROM FD
	WHERE FD_ID IN (
			SELECT MAX(FD_ID) FD_ID
			FROM FD
			WHERE [DATE] <= '11/5/2013'
			GROUP BY KBCI_NO
			)
		AND BALANCE > 1
	) FDR ON M.KBCI_NO = FDR.KBCI_NO
where m.kbci_no= '1300270'


select * from 
(
SELECT
	 A.KBCI_NO
	,CASE WHEN A.MI IS NULL THEN 
	 A.LNAME + ', ' + A.FNAME 
	 ELSE
	 A.LNAME + ', ' + A.FNAME + ' ' + ISNULL(A.MI,'') + '.'
	 END NAME
	,B.BALANCE
FROM 
MEMBERS A
JOIN
(SELECT X.KBCI_NO, SUM(X.CREDIT) - SUM(X.DEBIT) BALANCE
FROM (select KBCI_NO, CASE WHEN DRCR='DR' THEN AMOUNT END DEBIT, CASE WHEN DRCR='CR' THEN AMOUNT END CREDIT from FD WHERE [DATE]<='10/16/2013') X
GROUP BY  KBCI_NO AND
--HAVING SUM(X.CREDIT) - SUM(X.DEBIT) > 1
) B
ON A.KBCI_NO=B.KBCI_NO
) x
where x.kbci_no= '1300270'

select * from members